name: eda
channels:
  - defaults
dependencies:
  - python=3.8.17
  - pip=23.1.2
  - pip:
      - wandb==0.15.5
      - jupyter==1.0.0
      - seaborn==0.12.2
      - pandas==2.0.3
      - ydata-profiling==4.4.0
      - pyarrow==12.0.1 