name: download_file
channels:
  - defaults
dependencies:
  - python=3.8.17
  - pip=23.1.2
  - pip:
      - wandb==0.15.5
      - requests==2.31.0
      - mlflow==2.5.0
      - scikit-learn==1.3.0
      # - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
