name: nyc_airbnb_dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.17
  - pip=23.1.2
  - git=2.30.2
  - pip:
      - wandb==0.15.5
      - mlflow==2.5.0
      - ipython==8.12.0
      - notebook==7.0.1
      - jupyterlab==4.0.3
      - cookiecutter==2.2.3
      - hydra-core==1.3.2
      - matplotlib==3.7.2
      - pandas==2.0.3
