name: train_random_forest
channels:
  - defaults
dependencies:
  - python=3.8.17
  - pip=23.1.2
  - pip:
      - wandb==0.15.5
      - pandas==2.0.3
      - mlflow==2.5.0
      - scikit-learn==1.3.0
      - matplotlib==3.7.2
      - pillow==10.0.0
